"""
models.py — Pydantic models for TutorTrack AI.
Adapted from the Guesthouse Booking app:
  - Guest Name       → Student Name
  - Check-in Date    → Test Date
  - Room Price       → Marks Obtained
"""
from __future__ import annotations
from enum import Enum
from typing import Optional
from pydantic import BaseModel, EmailStr, field_validator, model_validator
import re


# ══════════════════════════════════════════════════════════════════
#  ENUMS
# ══════════════════════════════════════════════════════════════════

class RecordStatus(str, Enum):
    Pending   = "Pending"
    Reviewed  = "Reviewed"
    Archived  = "Archived"


class Grade(str, Enum):
    """Descriptive grade band derived from marks_obtained."""
    Outstanding = "Outstanding"   # 90–100
    Excellent   = "Excellent"     # 75–89
    Good        = "Good"          # 60–74
    Average     = "Average"       # 40–59
    NeedsWork   = "Needs Work"    # 0–39


# ══════════════════════════════════════════════════════════════════
#  STUDENT RECORD — CREATE (public endpoint, no auth required)
# ══════════════════════════════════════════════════════════════════

class StudentRecordCreate(BaseModel):
    # Optional numeric ID generated by the frontend for its own tracking
    id: Optional[int] = None

    # ── Core fields (guesthouse analogy) ───────────────────────────────────
    student_name: str          # was: name (Guest Name)
    test_date: str             # was: checkin (Check-in Date) — YYYY-MM-DD
    marks_obtained: float      # was: room_price (Room Price) — 0.0 – 100.0

    # ── Additional teacher-relevant fields ─────────────────────────────────
    subject: str
    class_name: str            # e.g. "Grade 6B"
    roll_number: str
    max_marks: float = 100.0
    remarks: str = ""
    timestamp: Optional[str] = None    # server-set; frontend value is overridden

    # ── Validators ─────────────────────────────────────────────────────────

    @field_validator("student_name", "subject", "class_name", "roll_number")
    @classmethod
    def not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()

    @field_validator("marks_obtained")
    @classmethod
    def valid_marks(cls, v: float) -> float:
        if not 0.0 <= v <= 100.0:
            raise ValueError("Marks must be between 0 and 100")
        return v

    @field_validator("max_marks")
    @classmethod
    def valid_max_marks(cls, v: float) -> float:
        if not 1.0 <= v <= 100.0:
            raise ValueError("Max marks must be between 1 and 100")
        return v

    @model_validator(mode="after")
    def marks_within_max(self) -> "StudentRecordCreate":
        if self.marks_obtained > self.max_marks:
            raise ValueError("Marks obtained cannot exceed max marks")
        return self


# ══════════════════════════════════════════════════════════════════
#  STUDENT RECORD — STATUS UPDATE (admin endpoint)
# ══════════════════════════════════════════════════════════════════

class StatusUpdate(BaseModel):
    status: RecordStatus
    notes: Optional[str] = None   # optional admin note on review/archive


# ══════════════════════════════════════════════════════════════════
#  STUDENT RECORD — RESPONSE (returned to frontend)
# ══════════════════════════════════════════════════════════════════

class StudentRecordResponse(BaseModel):
    fbDocId: str                        # Firestore document ID
    id: int                             # Numeric timestamp ID used by UI
    student_name: str
    test_date: str
    marks_obtained: float
    subject: str
    class_name: str
    roll_number: str
    max_marks: float
    remarks: str = ""
    timestamp: str
    status: RecordStatus
    grade: Grade                        # auto-computed grade band
    notes: Optional[str] = None

    class Config:
        use_enum_values = True


# ══════════════════════════════════════════════════════════════════
#  AUTH
# ══════════════════════════════════════════════════════════════════

class LoginRequest(BaseModel):
    uid: str
    password: str


class LoginResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in_seconds: int


class ChangePasswordRequest(BaseModel):
    current_password: str
    new_password: str

    @field_validator("new_password")
    @classmethod
    def strong_password(cls, v: str) -> str:
        if len(v) < 8:
            raise ValueError("Password must be at least 8 characters")
        return v


# ══════════════════════════════════════════════════════════════════
#  GENERIC RESPONSES
# ══════════════════════════════════════════════════════════════════

class MessageResponse(BaseModel):
    message: str
    detail: Optional[str] = None


# ══════════════════════════════════════════════════════════════════
#  ANALYTICS — class summary response
# ══════════════════════════════════════════════════════════════════

class ClassAnalytics(BaseModel):
    class_name: str
    subject: str
    total_students: int
    average_marks: float
    highest_marks: float
    lowest_marks: float
    grade_distribution: dict   # {"Outstanding": 3, "Excellent": 5, ...}
